hostname: &hostname grafana.yas.local.com
alertmanager:
  enabled: false
prometheusOperator:
  resources:
    requests:
      memory: 64Mi
    limits:
      memory: 128Mi
kube-state-metrics:
  resources:
    requests:
      memory: 32Mi
    limits:
      memory: 64Mi
prometheus-node-exporter:
  resources:
    requests:
      memory: 16Mi
    limits:
      memory: 32Mi
prometheus:
  prometheusSpec:
    enableRemoteWriteReceiver: true
    resources:
      requests:
        memory: 256Mi
      limits:
        memory: 512Mi
grafana:
  assertNoLeakedSecrets: false
  resources:
    requests:
      memory: 128Mi
    limits:
      memory: 256Mi
  sidecar:
    resources:
      requests:
        memory: 32Mi
      limits:
        memory: 64Mi
  grafana.ini:
    database:
      type: postgres
      host: postgresql.postgres:5432
      name: grafana
      user: yasadminuser
      password: admin
      ssl_mode: require
  adminUser: admin
  adminPassword: admin
  ingress:
    ingressClassName: nginx
    enabled: true
    hosts:
      - *hostname
