# .github/workflows/ci-backoffice-bff.yaml
name: CI - Backoffice Bff Service

on:
  push:
    branches:
      - '**'
    paths:
      - 'backoffice-bff/**'
      - '!backoffice-bff/**.md'
  workflow_dispatch:

jobs:
  build-and-push:
    uses: ./.github/workflows/ci-build-push.yaml
    with:
      service_name: backoffice-bff
    secrets:
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
