# .github/workflows/ci-backoffice-bff.yaml
name: CI - Backoffice Bff Service

on:
  push:
    branches:
      - '**'
    paths:
      - 'backoffice-bff/**'
      - '!backoffice-bff/**.md'
  workflow_dispatch:

jobs:
  build-and-push:
    uses: ./.github/workflows/ci-build-push.yaml
    with:
      service_name: backoffice-bff
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
