# .github/workflows/ci-customer.yaml
name: CI - Customer Service

on:
  push:
    branches:
      - '**'
    paths:
      - 'customer/**'
      - '!customer/**.md'
  workflow_dispatch:

jobs:
  build-and-push:
    uses: ./.github/workflows/ci-build-push.yaml
    with:
      service_name: customer
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
