# .github/workflows/ci-cart.yaml
name: CI - Cart Service

on:
  push:
    branches:
      - '**'
    paths:
      - 'cart/**'
      - '!cart/**.md'
  workflow_dispatch:

jobs:
  build-and-push:
    uses: ./.github/workflows/ci-build-push.yaml
    with:
      service_name: cart
    secrets:
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
