# .github/workflows/ci-location.yaml
name: CI - Location Service

on:
  push:
    branches:
      - '**'
    paths:
      - 'location/**'
      - '!location/**.md'
  workflow_dispatch:

jobs:
  build-and-push:
    uses: ./.github/workflows/ci-build-push.yaml
    with:
      service_name: location
    secrets:
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
