# .github/workflows/ci-media.yaml
name: CI - Media Service

on:
  push:
    branches:
      - '**'
    paths:
      - 'media/**'
      - '!media/**.md'
  workflow_dispatch:

jobs:
  build-and-push:
    uses: ./.github/workflows/ci-build-push.yaml
    with:
      service_name: media
    secrets:
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
