# .github/workflows/ci-order.yaml
name: CI - Order Service

on:
  push:
    branches:
      - '**'
    paths:
      - 'order/**'
      - '!order/**.md'
  workflow_dispatch:

jobs:
  build-and-push:
    uses: ./.github/workflows/ci-build-push.yaml
    with:
      service_name: order
    secrets:
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
