# .github/workflows/ci-payment.yaml
name: CI - Payment Service

on:
  push:
    branches:
      - '**'
    paths:
      - 'payment/**'
      - '!payment/**.md'
  workflow_dispatch:

jobs:
  build-and-push:
    uses: ./.github/workflows/ci-build-push.yaml
    with:
      service_name: payment
    secrets:
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
