# .github/workflows/ci-product.yaml
name: CI - Product Service

on:
  push:
    branches:
      - '**'
    paths:
      - 'product/**'
      - '!product/**.md'
  workflow_dispatch:

jobs:
  build-and-push:
    uses: ./.github/workflows/ci-build-push.yaml
    with:
      service_name: product
    secrets:
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
