# .github/workflows/ci-promotion.yaml
name: CI - Promotion Service

on:
  push:
    branches:
      - '**'
    paths:
      - 'promotion/**'
      - '!promotion/**.md'
  workflow_dispatch:

jobs:
  build-and-push:
    uses: ./.github/workflows/ci-build-push.yaml
    with:
      service_name: promotion
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
