# .github/workflows/ci-recommendation.yaml
name: CI - Recommendation Service

on:
  push:
    branches:
      - '**'
    paths:
      - 'recommendation/**'
      - '!recommendation/**.md'
  workflow_dispatch:

jobs:
  build-and-push:
    uses: ./.github/workflows/ci-build-push.yaml
    with:
      service_name: recommendation
    secrets:
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
