# .github/workflows/ci-rating.yaml
name: CI - Rating Service

on:
  push:
    branches:
      - '**'
    paths:
      - 'rating/**'
      - '!rating/**.md'
  workflow_dispatch:

jobs:
  build-and-push:
    uses: ./.github/workflows/ci-build-push.yaml
    with:
      service_name: rating
    secrets:
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
