# .github/workflows/ci-search.yaml
name: CI - Search Service

on:
  push:
    branches:
      - '**'
    paths:
      - 'search/**'
      - '!search/**.md'
  workflow_dispatch:

jobs:
  build-and-push:
    uses: ./.github/workflows/ci-build-push.yaml
    with:
      service_name: search
    secrets:
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
