# .github/workflows/ci-sampledata.yaml
name: CI - Sampledata Service

on:
  push:
    branches:
      - '**'
    paths:
      - 'sampledata/**'
      - '!sampledata/**.md'
  workflow_dispatch:

jobs:
  build-and-push:
    uses: ./.github/workflows/ci-build-push.yaml
    with:
      service_name: sampledata
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
