# .github/workflows/ci-sampledata.yaml
name: CI - Sampledata Service

on:
  push:
    branches:
      - '**'
    paths:
      - 'sampledata/**'
      - '!sampledata/**.md'
  workflow_dispatch:

jobs:
  build-and-push:
    uses: ./.github/workflows/ci-build-push.yaml
    with:
      service_name: sampledata
    secrets:
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
