# .github/workflows/ci-tax.yaml
name: CI - Tax Service

on:
  push:
    branches:
      - '**'
    paths:
      - 'tax/**'
      - '!tax/**.md'
  workflow_dispatch:

jobs:
  build-and-push:
    uses: ./.github/workflows/ci-build-push.yaml
    with:
      service_name: tax
    secrets:
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
