# .github/workflows/ci-webhook.yaml
name: CI - Webhook Service

on:
  push:
    branches:
      - '**'
    paths:
      - 'webhook/**'
      - '!webhook/**.md'
  workflow_dispatch:

jobs:
  build-and-push:
    uses: ./.github/workflows/ci-build-push.yaml
    with:
      service_name: webhook
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
